apiVersion: v1
kind: ConfigMap

metadata:
  name: aws-auth
  namespace: kube-system
  creationTimestamp: "2026-05-10T10:01:39Z"
  uid: d97ac9c0-e2dd-4ba9-acbc-bccf4798dd52

data:
  mapRoles: |
    - rolearn: arn:aws:iam::258180561417:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-tHxUluhlKtwH
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::258180561417:user/suresh
      username: suresh
      groups:
        - default-trainee
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-10T10:01:39Z"
  name: aws-auth
  namespace: kube-system
  uid: d97ac9c0-e2dd-4ba9-acbc-bccf4798dd52




