apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::258180561417:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-tHxUluhlKtwH
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::258180561417:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-10T10:01:39Z"
  name: aws-auth
  namespace: kube-system
  uid: d97ac9c0-e2dd-4ba9-acbc-bccf4798dd52

